window.mt = window.mt || {}; window.mt.data = {
	"assets": {
		"name": "assets",
		"contents": [
			{
				"name": "Loading",
				"contents": [
					{
						"id": 1,
						"name": "preload.png",
						"fullPath": "/Loading/preload.png",
						"key": "/loading.png",
						"width": 190,
						"height": 9,
						"frameWidth": 190,
						"frameHeight": 9,
						"frameMax": -1,
						"margin": 0,
						"spacing": 0,
						"anchorX": 0,
						"anchorY": 0,
						"fps": 10,
						"updated": 1406817915033,
						"atlas": ""
					},
					{
						"id": 2,
						"name": "loading.png",
						"fullPath": "/Loading/loading.png",
						"key": "/preload.png",
						"width": 190,
						"height": 9,
						"frameWidth": 190,
						"frameHeight": 9,
						"frameMax": -1,
						"margin": 0,
						"spacing": 0,
						"anchorX": 0,
						"anchorY": 0,
						"fps": 10,
						"updated": 1406817917030,
						"atlas": ""
					}
				],
				"count": 0,
				"id": 4,
				"fullPath": "/Loading",
				"isClosed": true
			},
			{
				"id": 5,
				"name": "pendulum_head.png",
				"fullPath": "/pendulum_head.png",
				"key": "/pendulum_head.png",
				"width": 49,
				"height": 49,
				"frameWidth": 49,
				"frameHeight": 49,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1408845370728,
				"atlas": ""
			},
			{
				"id": 6,
				"name": "pendulum_head.png",
				"fullPath": "/pendulum_head.png",
				"key": "/pendulum_head.png",
				"width": 49,
				"height": 49,
				"frameWidth": 49,
				"frameHeight": 49,
				"frameMax": -1,
				"margin": 0,
				"spacing": 0,
				"anchorX": 0,
				"anchorY": 0,
				"fps": 10,
				"updated": 1408845370728,
				"atlas": ""
			}
		],
		"count": 6
	},
	"objects": {
		"name": "objects",
		"contents": [
			{
				"id": "tmp1406818026618",
				"name": "Loading",
				"x": 0,
				"y": 0,
				"angle": 0,
				"contents": [
					{
						"assetId": 2,
						"x": 256,
						"y": 192,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"width": 190,
						"height": 9,
						"id": "tmp1406818026617",
						"name": "loading",
						"fullPath": "/Loading/loading",
						"assetKey": "/preload.png"
					},
					{
						"assetId": 1,
						"x": 256,
						"y": 192,
						"type": 0,
						"anchorX": 0,
						"anchorY": 0,
						"scaleX": 1,
						"scaleY": 1,
						"angle": 0,
						"alpha": 1,
						"frame": 0,
						"isVisible": 1,
						"isLocked": 0,
						"width": 190,
						"height": 9,
						"id": "tmp1406818026616",
						"name": "preload",
						"fullPath": "/Loading/preload",
						"assetKey": "/loading.png"
					}
				],
				"isVisible": false,
				"isLocked": true,
				"isFixedToCamera": 0,
				"fullPath": "/Loading",
				"isClosed": true
			},
			{
				"assetId": 6,
				"x": 192,
				"y": 384,
				"type": 0,
				"anchorX": 0,
				"anchorY": 0,
				"scaleX": 1,
				"scaleY": 1,
				"angle": 0,
				"alpha": 1,
				"frame": 0,
				"isVisible": 1,
				"isLocked": 0,
				"width": 49,
				"height": 49,
				"id": "tmp1408845436828",
				"name": "pendulum_head10",
				"fullPath": "/pendulum_head10",
				"assetKey": "/pendulum_head.png"
			},
			{
				"assetId": 6,
				"x": 128,
				"y": 256,
				"type": 0,
				"anchorX": 0,
				"anchorY": 0,
				"scaleX": 1,
				"scaleY": 1,
				"angle": 0,
				"alpha": 1,
				"frame": 0,
				"isVisible": 1,
				"isLocked": 0,
				"width": 49,
				"height": 49,
				"id": "tmp1408845436827",
				"name": "pendulum_head9",
				"fullPath": "/pendulum_head9",
				"assetKey": "/pendulum_head.png"
			},
			{
				"assetId": 6,
				"x": 64,
				"y": 320,
				"type": 0,
				"anchorX": 0,
				"anchorY": 0,
				"scaleX": 1,
				"scaleY": 1,
				"angle": 0,
				"alpha": 1,
				"frame": 0,
				"isVisible": 1,
				"isLocked": 0,
				"width": 49,
				"height": 49,
				"id": "tmp1408845436826",
				"name": "pendulum_head8",
				"fullPath": "/pendulum_head8",
				"assetKey": "/pendulum_head.png"
			},
			{
				"assetId": 6,
				"x": 0,
				"y": 128,
				"type": 0,
				"anchorX": 0,
				"anchorY": 0,
				"scaleX": 1,
				"scaleY": 1,
				"angle": 0,
				"alpha": 1,
				"frame": 0,
				"isVisible": 1,
				"isLocked": 0,
				"width": 49,
				"height": 49,
				"id": "tmp1408845436825",
				"name": "pendulum_head7",
				"fullPath": "/pendulum_head7",
				"assetKey": "/pendulum_head.png"
			},
			{
				"assetId": 6,
				"x": 64,
				"y": 64,
				"type": 0,
				"anchorX": 0,
				"anchorY": 0,
				"scaleX": 1,
				"scaleY": 1,
				"angle": 0,
				"alpha": 1,
				"frame": 0,
				"isVisible": 1,
				"isLocked": 0,
				"width": 49,
				"height": 49,
				"id": "tmp1408845436824",
				"name": "pendulum_head6",
				"fullPath": "/pendulum_head6",
				"assetKey": "/pendulum_head.png"
			},
			{
				"assetId": 6,
				"x": 0,
				"y": 0,
				"type": 0,
				"anchorX": 0,
				"anchorY": 0,
				"scaleX": 1,
				"scaleY": 1,
				"angle": 0,
				"alpha": 1,
				"frame": 0,
				"isVisible": 1,
				"isLocked": 0,
				"width": 49,
				"height": 49,
				"id": "tmp1408845436823",
				"name": "pendulum_head5",
				"fullPath": "/pendulum_head5",
				"assetKey": "/pendulum_head.png"
			},
			{
				"assetId": 6,
				"x": 192,
				"y": 128,
				"type": 0,
				"anchorX": 0,
				"anchorY": 0,
				"scaleX": 1,
				"scaleY": 1,
				"angle": 0,
				"alpha": 1,
				"frame": 0,
				"isVisible": 1,
				"isLocked": 0,
				"width": 49,
				"height": 49,
				"id": "tmp1408845436822",
				"name": "pendulum_head4",
				"fullPath": "/pendulum_head4",
				"assetKey": "/pendulum_head.png"
			},
			{
				"assetId": 6,
				"x": 448,
				"y": 256,
				"type": 0,
				"anchorX": 0,
				"anchorY": 0,
				"scaleX": 1,
				"scaleY": 1,
				"angle": 0,
				"alpha": 1,
				"frame": 0,
				"isVisible": 1,
				"isLocked": 0,
				"width": 49,
				"height": 49,
				"id": "tmp1408845436821",
				"name": "pendulum_head3",
				"fullPath": "/pendulum_head3",
				"assetKey": "/pendulum_head.png"
			},
			{
				"assetId": 6,
				"x": 384,
				"y": 128,
				"type": 0,
				"anchorX": 0,
				"anchorY": 0,
				"scaleX": 1,
				"scaleY": 1,
				"angle": 0,
				"alpha": 1,
				"frame": 0,
				"isVisible": 1,
				"isLocked": 0,
				"width": 49,
				"height": 49,
				"id": "tmp1408845436820",
				"name": "pendulum_head2",
				"fullPath": "/pendulum_head2",
				"assetKey": "/pendulum_head.png"
			},
			{
				"assetId": 5,
				"x": 128,
				"y": 128,
				"type": 0,
				"anchorX": 0,
				"anchorY": 0,
				"scaleX": 1,
				"scaleY": 1,
				"angle": 0,
				"alpha": 1,
				"frame": 0,
				"isVisible": 1,
				"isLocked": 0,
				"width": 49,
				"height": 49,
				"id": "tmp1408845335457",
				"name": "pendulum_head1",
				"fullPath": "/pendulum_head1",
				"assetKey": "/pendulum_head.png"
			},
			{
				"assetId": 5,
				"x": 256,
				"y": 256,
				"type": 0,
				"anchorX": 0,
				"anchorY": 0,
				"scaleX": 1,
				"scaleY": 1,
				"angle": 0,
				"alpha": 1,
				"frame": 0,
				"isVisible": 1,
				"isLocked": 0,
				"width": 49,
				"height": 49,
				"id": "tmp1408845335456",
				"name": "pendulum_head",
				"fullPath": "/pendulum_head",
				"assetKey": "/pendulum_head.png"
			}
		],
		"count": 0
	},
	"map": {
		"cameraX": 0,
		"cameraY": 0,
		"worldWidth": 800,
		"worldHeight": 480,
		"viewportWidth": 800,
		"viewportHeight": 480,
		"gridX": 64,
		"gridY": 64,
		"gridOffsetX": 0,
		"gridOffsetY": 0,
		"showGrid": 1,
		"backgroundColor": "#222222"
	}
};